### Search
POST http://localhost:3000/search
content-type: application/json

{
    "query": "select id, timestamp, message from logs where timestamp > datetime('now', '-5 minutes')"
}

### Log
POST http://localhost:3000/logs
